version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10-browsers

    working_directory: /go/src/github.com/alext/heating-controller
    steps:
      - checkout
      - run: make test
