// Code generated by "stringer -type=Action"; DO NOT EDIT.

package controller

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Off-0]
	_ = x[On-1]
	_ = x[SetTarget-2]
	_ = x[IncreaseTarget-3]
	_ = x[DecreaseTarget-4]
}

const _Action_name = "OffOnSetTargetIncreaseTargetDecreaseTarget"

var _Action_index = [...]uint8{0, 3, 5, 14, 28, 42}

func (i Action) String() string {
	if i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
